//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_LCE_Tweaker_Studio.Expoint {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class InAppUserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static InAppUserSettings defaultInstance = ((InAppUserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InAppUserSettings())));
        
        public static InAppUserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsNewUser {
            get {
                return ((bool)(this["IsNewUser"]));
            }
            set {
                this["IsNewUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int S_Ins_Loc {
            get {
                return ((int)(this["S_Ins_Loc"]));
            }
            set {
                this["S_Ins_Loc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int S_Ins_Arc {
            get {
                return ((int)(this["S_Ins_Arc"]));
            }
            set {
                this["S_Ins_Arc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int S_Ins_Pck {
            get {
                return ((int)(this["S_Ins_Pck"]));
            }
            set {
                this["S_Ins_Pck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int S_Ins_Fui {
            get {
                return ((int)(this["S_Ins_Fui"]));
            }
            set {
                this["S_Ins_Fui"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int S_Ins_SPT {
            get {
                return ((int)(this["S_Ins_SPT"]));
            }
            set {
                this["S_Ins_SPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GAF_PATH {
            get {
                return ((string)(this["GAF_PATH"]));
            }
            set {
                this["GAF_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int S_Ins_Col {
            get {
                return ((int)(this["S_Ins_Col"]));
            }
            set {
                this["S_Ins_Col"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>null</string>\r\n  <string>null</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ClipboardTextCollection {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ClipboardTextCollection"]));
            }
            set {
                this["ClipboardTextCollection"] = value;
            }
        }
    }
}
